apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: test-container-01
        image: singhritesh85/project-repo:1.89
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1
      imagePullSecrets: 
      - name: regcred
